name: Convert Markdown to HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'diary/**'
      - 'convert.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
    
    - name: Convert Markdown to HTML
      run: |
        python convert.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/
        git commit -m "Update HTML files" || echo "No changes to commit"
        git push
